---
- name: Write defined values
  loop: "{{ sysctl_defaults + sysctl_extra }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    ignoreerrors: "{{ omit if item.ignoreerrors is undefined else item.ignoreerrors }}"
    reload: "{{ omit if item.reload is undefined else item.reload }}"
    sysctl_file: "{{ omit if item.sysctl_file is undefined else item.sysctl_file }}"
    sysctl_set: "{{ true if item.sysctl_set is undefined else item.sysctl_set }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - sysctl

...
